import type { PluginManifest } from "@/plugins/types";

export const knowledgeManifest: PluginManifest = {
  id: "knowledge",
  name: "Conhecimento",
  version: "1.1.0",
  description: "Wiki com busca semantica, sync Nextcloud e RAG para o assistente de IA.",
  icon: "BookOpen",
  nav: { label: "Conhecimento", href: "/knowledge", icon: "BookOpen", order: 70, group: "Conhecimento" },
  apiPrefix: "/api/v1/knowledge",
  settingsSchema: [
    {
      key: "enableSemanticSearch",
      label: "Busca semantica habilitada",
      type: "boolean",
      defaultValue: true,
    },
    {
      key: "autoIngest",
      label: "Indexar automaticamente no RAG",
      type: "boolean",
      defaultValue: true,
    },
    {
      key: "ragScanLimit",
      label: "Limite de embeddings na busca semantica",
      type: "number",
      defaultValue: 2000,
      description: "Quantidade maxima de chunks analisados por busca (padrao 2000).",
    },
    {
      key: "nextcloudEnabled",
      label: "Sincronizar com Nextcloud",
      type: "boolean",
      defaultValue: false,
    },
    {
      key: "nextcloudUrl",
      label: "URL do Nextcloud",
      type: "text",
      description: "Ex: https://cloud.conceptio.com.br",
      defaultValue: "",
    },
    {
      key: "nextcloudUsername",
      label: "Usuario Nextcloud",
      type: "text",
      defaultValue: "",
    },
    {
      key: "nextcloudAppPassword",
      label: "Senha de app",
      type: "secret",
      description: "Gere em Nextcloud > Configuracoes > Seguranca > Senhas de app",
    },
    {
      key: "nextcloudFolder",
      label: "Pasta do vault",
      type: "text",
      defaultValue: "LabFlow",
      description: "Pasta dentro dos arquivos do usuario (aceita subpastas .md)",
    },
  ],
  defaultSettings: {
    enableSemanticSearch: true,
    autoIngest: true,
    ragScanLimit: 2000,
    nextcloudEnabled: false,
    nextcloudUrl: "",
    nextcloudUsername: "",
    nextcloudAppPassword: "",
    nextcloudFolder: "LabFlow",
    nextcloudAutoSyncEnabled: false,
    nextcloudAutoSyncIntervalMinutes: 60,
    nextcloudFolderProjectMap: {},
    nextcloudExcludeFolders: ["templates"],
    nextcloudAdminOnlyFolders: ["admin"],
    nextcloudLastSyncAt: null,
    nextcloudLastSyncStatus: null,
    nextcloudLastSyncMessage: null,
    nextcloudLastSyncCount: 0,
  },
};
